### ISSUE TITLE
Aave - get user's supply & borrow tokens

### ISSUE THREAD

**Issue by KaymasJain** [Instadapp/dsa-resolvers#12]
Create a new function [here](https://github.com/Instadapp/dsa-resolvers/blob/main/contracts/protocols/mainnet/aave_v2/main.sol).

It'll take the user address as input and will return supply tokens and borrow tokens of the user.

For reference - https://docs.aave.com/developers/the-core-protocol/lendingpool#getuserconfiguration

**Comment by pradyuman-verma** [comment]
` return supply tokens and borrow tokens of the user.`
Do you mean it should just return the number of tokens the user has as collateral and the number of tokens the user has borrowed?
like if the user has supplied WETH as collateral and borrowed DAI, then it should return this ->
```
borrowed: 1 
supplied: 1
```
