### ISSUE TITLE
Update resolvers

### ISSUE THREAD

**Issue by KaymasJain** [Instadapp/dsa-resolvers#17]
- [x] Add Aave resolver to Avalanche (Will be same as [mainnet](https://github.com/Instadapp/dsa-resolvers/tree/main/contracts/protocols/mainnet/aave_v2) & [Polygon](https://github.com/Instadapp/dsa-resolvers/tree/main/contracts/protocols/polygon/aave_v2) with addresses change and maybe minor updates).
- [x] Add Uniswap resolver to Arbitrum (should be same as [mainnet](https://github.com/Instadapp/dsa-resolvers/tree/main/contracts/protocols/mainnet/uniswap))

**Comment by pradyuman-verma** [comment]
I think, now we should close this issue!
