### ISSUE TITLE
Add Morpho Aave V3 

### ISSUE THREAD

**Issue by shriyatyagii** [Instadapp/dsa-resolvers#97]
In morpho aave v3, we won't have a lens contract. We need to fetch and calculate all the data through [Morpho's core contracts](https://github.com/morpho-dao/morpho-aave-v3/tree/main/src).

Old morpho Lens contract - https://github.com/morpho-dao/morpho-v1/blob/main/src/aave-v2/lens/Lens.sol

We can use the getter functions included [here](https://github.com/morpho-dao/morpho-aave-v3/blob/main/src/MorphoGetters.sol)

You can take reference for the functions to include in the resolver from [morpho aave v2 resolver](https://github.com/Instadapp/dsa-resolvers/tree/main/contracts/protocols/mainnet/morpho/aave_v2).

The main functions and their return values will remain the same -

- `getPositionAll` returning `UserData` struct
- `getPosition` returning `UserData` struct
- `getMorphoConfig` returning `MorphoData` struct

Updates ->

- In struct UserData, add a new field `suppliedValue`, which will be the total supplied value, pure + collateral.

You can see if it would also make sense to return collateral values anywhere else^

**Comment by q1q0** [comment]
as you know we can fetch data only from MorphGetter.sol.
I think UserData struct will be like below:

```
struct LiquidityData {
    uint256 borrowable; 
    uint256 maxDebt;
    uint256 debt; 
}

struct UserData {
   LiquidityData liquidityData;
   address[] collateralList;
   address[] borrowList;
   address[] supplyList;
   address[] scaledCollateralList;
   address[] scaledP2PBorrowList;
   address[] scaledP2PSupplyList;
   address[] scaledPoolSupplyList;
   address[] nonceList;
   mapping(address=>uint256) collateralBalance;
   mapping(address=>uint256) borrowBalance;
   mapping(address=>uint256) supplyBalance;
   mapping(address=>uint256) scaledCollateralBalance;
   mapping(address=>uint256) scaledP2PBorrowBalance;
   mapping(address=>uint256) scaledP2PSupplyBalance;
   mapping(address=>uint256) scaledPoolSupplyBalance;
}
```
